version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root  # Задай свой пароль для root
      MYSQL_DATABASE: border         # Имя базы данных, которая будет создана
      MYSQL_USER: root                 # Имя пользователя
      MYSQL_PASSWORD: root       # Пароль пользователя
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  db_data:
